### ISSUE TITLE
INFRA: Add Docker Support

### ISSUE THREAD

**Issue by alpha037** [eraaxit/custom-json-generator#2]
- [x] #5

**Comment by alpha037** [comment]
Hey, @eraaxit, I'd like to work on this issue.

**Comment by eraaxit** [comment]
Hey @alpha037 , thanks for showing interest. But this project is in very beginning stage. When it would be ready to be deployed live, then you can add Docker functionality for sure, but for now you can raise any issue that could help in it's development and start working on it. Let us know your thoughts on this.

**Comment by alpha037** [comment]
Okay, that sounds good to me.
